version: '2'

services:
  bcash:
    image: purse/bcash
    container_name: bcash
    restart: unless-stopped
    ports:
      #-- Mainnet
      - "8333:8333"
      - "8332:8332" # RPC/HTTP
      - "8334:8334" # Wallet
      #-- Testnet
      #- "18333:18333"
      #- "18332:18332" # RPC/HTTP
      #- "18334:18334"
    environment:
      BCASH_CONFIG: /data/bcash.conf
      VIRTUAL_HOST: bcash.yourdomain.org
      VIRTUAL_PORT: 8332
      #VIRTUAL_PORT: 18332 # Testnest
    networks:
      - "bcash"
      - "nginx-proxy"
    volumes:
      - ~/.bcash:/data
      - ${PWD}/secrets/bcash.conf:/data/bcash.conf
      - ${PWD}/secrets/wallet.conf:/data/wallet.conf

  nginx_proxy:
    image: jwilder/nginx-proxy
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - "nginx-proxy"
    volumes:
      - ./secrets/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  bcash:
    external:
      name: "bcash"
  nginx-proxy:
    external:
      name: "nginx-proxy"
